# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 14:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата выхода')),
                ('ean', models.CharField(max_length=30, verbose_name='EAN')),
                ('cover_url', models.CharField(max_length=200, verbose_name='Обложка')),
                ('characters', models.TextField(verbose_name='Персонажи')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comic',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarvelComixStore.Customer', verbose_name='Заказчик'),
        ),
    ]
