# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarvelComixStore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='marvel_id',
            field=models.IntegerField(default=0),
        ),
    ]
